apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deploy-dev
spec:
  replicas: 1
  template:
    metadata:
     labels:
       app: nginx-deploy-dev
    spec:
      containers:
      - name: nginx-deploy-dev
        image: nginx:1.8
        ports:
        - containerPort: 80
