apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deploy-prod
spec:
  replicas: 1
  template:
    metadata:
     labels:
       app: nginx-deploy-prod
    spec:
      containers:
      - name: nginx-deploy-prod
        image: nginx:1.7.9
        ports:
        - containerPort: 80
